version: '2'

services:
  db:
   image: postgres
   ports:
         - 5432:5432
  app:
    image: golang
    container_name: golang_echo
    volumes:
      - ./:/go/
    ports:
      - 8081:8081
    working_dir: /go/app/
    command: ./app
    depends_on:
      - db
